pyramid's example
marshmallow-code/webargs pull request #158
Opened 2017-02-23 16:22 UTC by podhmo

Hello. This is a example for pyramid.

2017-02-23 16:24 UTC, podhmo commented
if TODO comments are a bit messy, I will remove it.

2017-02-24 01:25 UTC, sloria requested changes
Looks good! Just a few tiny changes and this is good to merge.

2017-02-24 01:25 UTC, sloria commented on examples/pyramid_example.py
> +    $ python examples/flask_example.py
This needs to be changed to `python examples/pyramid_example.py`

2017-02-24 01:25 UTC, sloria commented on examples/pyramid_example.py
> +# TODO: support
Can you remove these and report issues for the missing features you are referring to?

2017-02-24 01:59 UTC, podhmo commented on examples/pyramid_example.py
> +# TODO: support
OK. I will fix.

2017-02-24 02:11 UTC, podhmo commented
fixed (and squached).

2017-02-25 05:23 UTC, sloria approved these changes

2017-02-25 05:23 UTC, sloria commented
Thanks!

2017-02-25 05:23 UTC, merged