fix use_kwargs used with ma.Schema(partial=True|tuple)
marshmallow-code/webargs pull request #307
Opened 2018-10-22 09:14 UTC by TTWShell

We hope ignore missing fields when instance `ma.Schema` with `partial=True`.  
See https://marshmallow.readthedocs.io/en/3.0/api_reference.html#schema

2018-11-22 09:26 UTC, lafrech commented
Looks good to me.

You could parametrize the test to reduce duplication (pass (partial, expected_result) as tuple).

2018-11-22 10:03 UTC, TTWShell commented
@lafrech Thank you for taking your time for the review. Did you mean this?

	def test_use_kwargs_with_arg_missing_and_partial(web_request, parser):
	    class UserSchema(Schema):
	        id = fields.Int(dump_only=True)
	        email = fields.Email()
	        password = fields.Str(load_only=True)
	        if MARSHMALLOW_VERSION_INFO[0] < 3:

	            class Meta:
	                strict = True

	    web_request.json = {"email": "foo@bar.com"}
	    kwargs = deepcopy(strict_kwargs)

	    def assert_excepted(partial, expected_result):
	        kwargs['partial'] = partial

	        @parser.use_kwargs(UserSchema(**kwargs), web_request)
	        def viewfunc(**kwargs):
	            return kwargs

	        assert viewfunc() == expected_result

	    assert_excepted(True, {"email": "foo@bar.com"})
	    assert_excepted(["email"], {"email": "foo@bar.com", "password": missing})
	    assert_excepted(["password"], {"email": "foo@bar.com"})

2018-11-22 10:20 UTC, lafrech commented
I meant something like that. I could have been more explicit.

parametrize is probably my favorite pytest feature.

```py
@pytest.mark.parametrize('case', [
    (True, {"email": "foo@bar.com"})
    (["email"], {"email": "foo@bar.com", "password": missing}),
    (["email"], {"email": "foo@bar.com"}),
])
def test_use_kwargs_with_arg_missing_and_partial(web_request, parser, case):
    partial, expected = params

    class UserSchema(Schema):
        id = fields.Int(dump_only=True)
        email = fields.Email()
        password = fields.Str(load_only=True)
        if MARSHMALLOW_VERSION_INFO[0] < 3:
            class Meta:
                strict = True

    web_request.json = {"email": "foo@bar.com"}
    kwargs = deepcopy(strict_kwargs)
    kwargs["partial"] = partial

    @parser.use_kwargs(UserSchema(**kwargs), web_request)
    def viewfunc(**kwargs):
        return kwargs
    assert viewfunc() == expected

```

2018-11-22 11:46 UTC, TTWShell commented
@lafrech updated and test passed.

2018-11-22 12:50 UTC, lafrech commented on tests/test_core.py
> +    @parser.use_kwargs(UserSchema(**kwargs), web_request)
Suggestion:

- remove `import deepcopy`

- `UserSchema(partial=partial, **kwargs)`

2018-11-22 14:45 UTC, sloria requested changes
I'm unsure about this change.

With this change, the number of arguments to the decorated view will vary. Therefore you can't use named arguments.

```python
# won't work
@parser.use_kwargs(UserSchema(partial=True))
def viewfunc(request, username, password):
```

You could, of course, use `**kwargs` instead of named arguments, but at that point you might as well use `use_args` instead.

Am I missing something?

2018-11-23 01:10 UTC, TTWShell commented
Thanks.

We want used like this:

	class UserSchema(ModelSchema):
		username =  fields.Str(required=True)
		password =  fields.Str(required=True)
		# other optinal fields auto generated by ModelSchema ...


	@bp.route('/users', methods=['POST'])
	@use_kwargs(UserSchema(partial=True))
	create_user(username, password, **kwargs):
	    User(username=username, password=password, **kwargs)


Named arguments mean that required, others in kwargs as optinal.

Explicit is better than implicit.

2018-11-23 08:01 UTC, lafrech commented
You could do 

```py
class UserSchema(ModelSchema):
	username =  fields.Str(missing=username)
	password =  fields.Str(missing=password)
	# other optional fields auto generated by ModelSchema ...

@bp.route('/users', methods=['POST'])
@use_kwargs(UserSchema(partial=True))
create_user(**kwargs):
    User(**kwargs)
```

I didn't really think about the use case. I don't think this change forces anything on users (if you don't use partial, it makes not different, and if you do, the new behaviour is more consistent).

AFAIU, the question here is whether using partial is a good idea.

2018-11-23 10:06 UTC, TTWShell commented
partial (bool|tuple) – Whether to ignore missing fields. If its value is an iterable, only missing fields listed in that iterable will be ignored.

`use_kwargs` force fill_in_missing_args, so `partial` won't work as excepted.

    @use_kwargs(UserSchema(partial=False))
    create_user(username, password, **kwargs):
        User(username=username, password=password, **kwargs)

`kwargs` will be contain `marshmallow.utils.missing` value field. This is not expected.

2018-11-26 15:25 UTC, GreenSmile commented
Guys, there is similar issue related to `force_all` and `fill_in_missing_args()`: https://github.com/sloria/webargs/issues/252

I believe the proper solution for both issues would be extra `use_kwargs()` parameter to ignore `force_all`. This way you will be able to disable `fill_in_missing_args()`, so any changes applied to data by Marshmallow will be preserved. This  solution is backward compatible and solves both issues at once. Something like:

```
@use_kwargs(UserSchema(), partial=True)  # Note: partial is parameter of use_kwargs.
def create_user(username, password, **kwargs):
    User(username=username, password=password, **kwargs)
```

or as I use it:
```
@use_kwargs(UserSchema(), partial=True)
def update_user(user_id, **kwargs):
    user = read_user(user_id)
    for key, value in kwargs.items():
        setattr(user, key, value)
    user.save()
```

2018-12-24 14:29 UTC, sloria commented
I think I'm leaning towards @GreenSmile 's suggestion. Exposing a way to disable the `fill_in_missing_args()` call is a minimally impactful change, and it solves the OP and #252. I'm not sure about the name `partial` for the new param, though--users may confuse it with marshmallow's `partial`. ~~Maybe `fill_missing`?~~ `Parser.parse` already has a `force_all` param; how about we expose it to use_args/use_kwargs?

@TTWShell @lafrech Thoughts?

EDIT: Suggest `force_all` instead of `fill_missing`.

2018-12-25 21:16 UTC, sloria commented
I've added the `force_all` argument to use_kwargs to provide a backwards-compatible solution to this issue and #252. So I'm going to close this for now.

I think we should just remove the `fill_in_missing_args` behavior. I've opened an RFC: #342. Please comment there if you have thoughts/opinions.

2018-12-25 21:17 UTC, closed without merging