Don't pass a status_code as kwargs in a Field validator
marshmallow-code/webargs pull request #328
Opened 2018-11-22 10:59 UTC by lafrech

Closes #327.

With this change, the naming of `DEFAULT_VALIDATION_STATUS` is a bit improper, but we can leave it as is to avoid breaking stuff everywhere.

2018-12-24 14:56 UTC, sloria requested changes
Just one suggested change.

There are a few tests in `tests/test_core.py:TestValidationError` will need to be modified/removed.

2018-12-24 14:56 UTC, sloria commented on webargs/core.py
>          self.status_code = status_code
This should be removed, since it will no longer be respected.

2018-12-30 21:26 UTC, lafrech commented
Just rebased.

I also went ahead with the removal of `webargs.ValidationError`. It results in further code simplification (I mean removal) in `_on_validation_error`. Nice.

2018-12-30 22:38 UTC, sloria approved these changes

2018-12-30 22:39 UTC, merged