BUG: create boolean check for location type allowing more options on marshmellow Field
marshmallow-code/webargs pull request #332
Opened 2018-12-01 20:15 UTC by attack68

I have the following use-pattern, which involves transmitting an image file in some cases and in others a string as part of a form:

    'args': {"id": fields.Int(required=True), "image": fields.Field(location=('files', 'form'), allow_blank=True)}

This failed since the location input of Field was converted to a list before converting to a set in upon validation, here:

    def _validated_locations(self, locations):
        """Ensure that the given locations argument is valid.

        :raises: ValueError if a given locations includes an invalid location.
        """
        # The set difference between the given locations and the available locations
        # will be the set of invalid locations
        valid_locations = set(self.__location_map__.keys())
        given = set(locations)

 However the commit change permits this and is backwards compatible for regular single item string inputs.

2018-12-02 18:10 UTC, sloria requested changes
Thanks for the PR!

I wouldn't consider this a bug fix since we don't currently support passing multiple locations to a field.

That said, I'm open to adding this. Can you please add a test for this and--if you have time--update any relevant docs?

2018-12-02 18:10 UTC, sloria commented on webargs/core.py
> +            if isinstance(location, tuple) or isinstance(location, list):
This can be simplified to

```suggestion
            if isinstance(location, (list, tuple)):
```

2018-12-18 09:23 UTC, attack68 commented
Sorry, have been very busy to look at this - will do if I get time. I was a bit put off by the extensive test failure report. It seemed to be a lot to go through and figure out what was going on from a newcomers perspective, for what I thought originally might be easy to slot it.

2018-12-18 14:19 UTC, sloria commented
@attack68 I understand. No rush to get to it if you don't have time.

The test failures are unrelated to this PR and have since been fixed. So if you rebase your branch with `dev` and force-push, the tests should pass.

2019-07-01 02:41 UTC, sloria commented
Closing for now, since this has gone stale. Feel free to re-open a PR if you're still interested in this.

2019-07-01 02:41 UTC, closed without merging