Add documentation about marshmallow-dataclass
marshmallow-code/webargs pull request #432
Opened 2019-10-10 14:56 UTC by CptSpaceToaster

Webargs already works out of the box with marshmallow-dataclass, however there are some tripping points one can run into if you miss the warnings associated with `use_kwargs`, which expects all schemas to deserialize into a dictionary. An assumption not maintained by marshmallow-dataclass _by design_

I've included a simple example of how I would use marshmallow-dataclass demonstrating how to deserialize requests into dataclasses with type hints.

Comments and feedback welcome.

2019-10-17 15:26 UTC, sloria requested changes
Perhaps the documentation should be more generic, since the issue is not really specific to marshmallow-dataclass. This is relevant when using any schema that implements a `post_load` method that returns an object rather than a dict.

2019-10-21 14:41 UTC, CptSpaceToaster commented
I'm totally up for making changes, however the issue is technically captured by the warning at the end of the [marshmallow integration](https://webargs.readthedocs.io/en/latest/advanced.html#marshmallow-integration) paragraph.

> **Warning**
> Any Schema passed to use_kwargs MUST deserialize to a dictionary of data. Keep this in mind when writing post_load methods.

For users writing their own post load methods, the documentation is _already_ trying to clear up those tripping points.  Maybe we could expand that warning into an entire section, and explicitly call out `marshmallow-dataclass` as an example?

2019-10-21 14:55 UTC, CptSpaceToaster commented
Maybe we could remove the warning, and write a section like this?

> When not to use `use_kwargs`
> -----------------------
> 
> Any Schema passed to use_kwargs MUST deserialize to a dictionary of data. If you are relying on schemas that provide `post_load` methods that end up transforming the result, then you should instead rely on use_args.
> 
> For example, marshmallow dataclass can be used to provide schemas built from python3 dataclasses. However, these schemas will deserialize content into a dataclass and NOT a dictionary.
> 
> ```python
>     from marshmallow_dataclass import dataclass
>     from webargs.flaskparser import use_args
> 
> 
>     @dataclass
>     class Greeting:
>         name: str
>         prefix: str = "Hello"
> 
> 
>     @use_args(Greeting.Schema)
>     def profile_posts(greeting: Greeting):
>         return f"{greeting.prefix} {greeting.name}"
> ```

`use_args` would link to the proper link in the doc. I'm tempted to make [marshmallow dataclass](https://github.com/lovasoa/marshmallow_dataclass) link to that project's github, but I'd like permission from maintainers here before I just assume that'd be Ok.

2019-10-21 15:31 UTC, sloria commented
@CptSpaceToaster I like that direction. Maybe we should exemplify usage with marshmallow-sqlalchemy? From what I can tell, marshmallow_dataclass isn't as popular, whereas I think many webargs users are already ma-sqla users. Perhaps you could write an example with a plain schema with a `post_load` method that returns an object, then include mention of libraries that generate schema (ma-sqla, ma_dataclass).

2019-10-26 17:14 UTC, CptSpaceToaster commented
Would love some feedback to see if the grammar and language are suitable!

2019-10-28 13:47 UTC, merged

2019-10-28 13:47 UTC, sloria commented
Thanks!