Fix dev requirements install
marshmallow-code/webargs pull request #973
Opened 2024-09-10 15:07 UTC by un4gt

The command `pip install -e '.[dev]'` results in a syntax error on some systems due to single quotes. 

In windows :

```
pip install -e '.[dev]'
ERROR: '.[dev]' is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
```

By using double quotes (`pip install -e ".[dev]"`), the command runs successfully on all platforms, ensuring better cross-platform compatibility.

2024-09-10 15:41 UTC, lafrech requested changes

2024-09-10 15:41 UTC, lafrech commented on .gitignore
> +.idea/
This doesn't belong in the project but in [your own .gitignore](https://stackoverflow.com/a/7335487/) (local to you computer, global to your projects).

2024-09-10 15:41 UTC, lafrech commented on CONTRIBUTING.rst
> +    $ pip install -e ".[dev]"
It even works without any quotes on my machine (Linux). Would that work on Windows?

    pip install -e .[dev]

2024-09-10 15:58 UTC, lafrech commented
The CI failure is unrelated and seems to be due to changes in bottle 0.13.

2024-09-10 16:07 UTC, sirosen commented
> The CI failure is unrelated and seems to be due to changes in bottle 0.13.

I'll plan to look into that either today or tomorrow.

2024-09-10 16:13 UTC, lafrech commented
Thanks Stephen.

It seems related to how unicode errors are treated but I haven't gotten to the bottom of it and I gotta go.

I scrolled through [bottle changelog](https://bottlepy.org/docs/dev/changelog.html#release-0-13) and nothing stroke me as relevant to this issue.

2024-09-10 17:15 UTC, un4gt commented on CONTRIBUTING.rst
> +    $ pip install -e ".[dev]"
single quote  is notworking on windows:

![image](https://github.com/user-attachments/assets/87041031-99ad-47d2-a184-a9d6fac6527e)

But, double quote and without quote works well.

I think we need to unify the commands.

2024-09-11 07:39 UTC, lafrech commented on CONTRIBUTING.rst
> +    $ pip install -e ".[dev]"
Sure. I don't know why we put those quotes in the first place so I'd go for no quotes at all if it works everywhere.

2024-09-11 14:48 UTC, sloria commented on CONTRIBUTING.rst
> +    $ pip install -e ".[dev]"
oops, on zsh the quotes are required

```
$ pip install -e .[dev]                              
zsh: no matches found: .[dev]
```

double quotes seems to work though, so i'm fine with this change as is

2024-09-11 14:49 UTC, sloria approved these changes

2024-09-11 14:52 UTC, merged

2024-09-11 14:53 UTC, lafrech commented on CONTRIBUTING.rst
> +    $ pip install -e ".[dev]"
OK so that's why we put those quotes in the first place. Double quotes is fine, then.